### ISSUE TITLE
Revise IsPlaceHolder handling

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.AndroidTv#2]
Don't hide play buttons on account of IsPlaceHolder. Instead, show a friendly message that it's not  playable from this app. The message is needed in case the content is sent to the player through other means.

**Comment by ebr11** [comment]
I don't reference the placeholder property specifically, I just key off of PlayAccess being "full" but isn't it better to do both?  I don't want to show play buttons for items that cannot be played but can also have the message at the lower level in case it is attempted by some other means.
