### ISSUE TITLE
Error on unlock payment

### ISSUE THREAD

**Issue by altf4** [MediaBrowser/MediaBrowser.AndroidTv#8]
After verifying my payment options:

```
Error
An error occurred. Please Try again. 
```

I wish there was more information to give. Here's a picture of it:

![emby-error](https://cloud.githubusercontent.com/assets/609563/7100362/92762786-dfd3-11e4-8f6b-5d68eabefc37.jpg)

Also: Having a paywall in front of a crippled app is kind of rude. Things like this happen. I wanted to spend the next few hours watching TV instead of side loading a modified app, but here we are.

**Comment by ebr11** [comment]
Do other in-app payments work on other apps?  Have you rooted the device or done anything else to hack the Play Store process?  That message is coming from the Google service, not us.

As for the paywall - It is clearly stated (in bold) in the app description plus there is a two week free trial of full functionality.

**Comment by altf4** [comment]
The device is an unmodified Nexus Player just purchased yesterday. Other purchases work fine, so I don't know what's up with that.

I wound up just buying a lifetime membership thing, and that seemed to do the trick. Playback works in the Android TV app now. I've been really impressed with Emby so far, so thanks!

**Comment by ebr11** [comment]
Okay, I'm not sure what was up with it either but the screen you were in was actually a part of the Google Play Store as opposed to our app so I guess something went wrong in that process.
