### ISSUE TITLE
Set new ClientCapabilities properties

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.AndroidTv#9]
This is becoming more ClientInfo than capabilities but anyway, set these properties:

Url - your store url
ImageUrl - host an image on github and use the raw url. Any size will do, but stick to 1:1 aspect ratio.

**Comment by ebr11** [comment]
What is the image for?

**Comment by LukePulverenti** [comment]
I ultimately want to remove the hardcoding of images into the server. With Dlna for example we can pull images from each device. I could do an image upload method instead but it's a little messier because you have to be able to find out info of the current image to avoid uploading over and over.

**Comment by ebr11** [comment]
Yes, but in what context?  You mean the little android man that overlays the active device tile?

**Comment by LukePulverenti** [comment]
Yes, I will change it to IconUrl as that's more appropriate.

**Comment by ebr11** [comment]
Okay.  What if I have more than one store link...?

**Comment by LukePulverenti** [comment]
Detect it at runtime. We can also use the links to periodically remind users to review their apps. So you want to make sure the right one is presented.

**Comment by LukePulverenti** [comment]
Since I'm already going to change to IconUrl, I'll change Url to AppStoreUrl to be explicit. Just in case we ever need a home Url later.

**Comment by ebr11** [comment]
Can you throw the little android man you are using now onto github and give me the url?  I think that is a good icon for the app.
